"""ApiKey(321)

Revision ID: 0d699c4dd495
Revises: 1eb10c2d272e
Create Date: 2025-05-12 16:01:07.402536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d699c4dd495'
down_revision: Union[str, None] = '1eb10c2d272e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('yandex_gpt_folder', sa.Text(), nullable=True))
    op.drop_column('api_keys', 'YANDEX_GPT_FOLDER')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('YANDEX_GPT_FOLDER', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('api_keys', 'yandex_gpt_folder')
    # ### end Alembic commands ###
