"""ApiKey(123)

Revision ID: 1eb10c2d272e
Revises: 0e4a9028ab47
Create Date: 2025-05-12 14:41:47.080034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb10c2d272e'
down_revision: Union[str, None] = '0e4a9028ab47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('YANDEX_GPT_FOLDER', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'YANDEX_GPT_FOLDER')
    # ### end Alembic commands ###
