"""ReviewFilter

Revision ID: a65635e2e900
Revises: 4960a885313c
Create Date: 2025-05-06 11:23:51.679116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65635e2e900'
down_revision: Union[str, None] = '4960a885313c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_filters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('RATING', sa.Integer(), nullable=True),
    sa.Column('HAS_TEXT', sa.Boolean(), nullable=True),
    sa.Column('IS_ACTIVE', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'api_keys', ['id'])
    op.create_unique_constraint(None, 'prompts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompts', type_='unique')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_table('review_filters')
    # ### end Alembic commands ###
